version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    groups:
      dev-deps:
        dependency-type: 'development'
        update-types:
          - minor
          - patch
      prod-deps:
        dependency-type: 'production'
        update-types:
          - minor
          - patch
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    groups:
      all-actions:
        patterns:
          - '*'
