name: CI

on:
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Setup
        uses: ./.github/actions/setup
      - name: Lint and format
        run: pnpm run ci
      - name: Build
        run: pnpm run build
      - name: Test
        run: pnpm run test
